/*
 * This file has been modified as part of the FreeMiNT project. See
 * the file Changes.MH for details and dates.
 */

/*
 * Copyright 1991,1992 Eric R. Smith.
 * Copyright 1992,1993,1994 Atari Corporation.
 * All rights reserved.
 */

# ifndef _mint_signal_h
# define _mint_signal_h

# include "ktypes.h"

typedef unsigned long int sigset_t;

# define NSIG		32		/* number of signals recognized */

# define SIGNULL	 0		/* not really a signal */
# define SIGHUP		 1		/* hangup signal */
# define SIGINT		 2		/* sent by ^C */
# define SIGQUIT	 3		/* quit signal */
# define SIGILL		 4		/* illegal instruction */
# define SIGTRAP	 5		/* trace trap */
# define SIGABRT	 6		/* abort signal */
# define SIGPRIV	 7		/* privilege violation */
# define SIGFPE		 8		/* divide by zero */
# define SIGKILL	 9		/* cannot be ignored */
# define SIGBUS		10		/* bus error */
# define SIGSEGV	11		/* illegal memory reference */
# define SIGSYS		12		/* bad argument to a system call */
# define SIGPIPE	13		/* broken pipe */
# define SIGALRM	14		/* alarm clock */
# define SIGTERM	15		/* software termination signal */
# define SIGURG		16		/* urgent condition on I/O channel */
# define SIGSTOP	17		/* stop signal not from terminal */
# define SIGTSTP	18		/* stop signal from terminal */
# define SIGCONT	19		/* continue stopped process */
# define SIGCHLD	20		/* child stopped or exited */
# define SIGTTIN	21		/* read by background process */
# define SIGTTOU	22		/* write by background process */
# define SIGIO		23		/* I/O possible on a descriptor */
# define SIGXCPU	24		/* CPU time exhausted */
# define SIGXFSZ	25		/* file size limited exceeded */
# define SIGVTALRM	26		/* virtual timer alarm */
# define SIGPROF	27		/* profiling timer expired */
# define SIGWINCH	28		/* window size changed */
# define SIGUSR1	29		/* user signal 1 */
# define SIGUSR2	30		/* user signal 2 */
# define SIGPWR		31		/* power failure (restart) */

/* XXX which signals are not maskable? */
# define UNMASKABLE (1L | (1L << SIGKILL) | (1L << SIGCONT) | (1L << SIGSTOP))

/* XXX which signals are stop signals? */
# define STOPSIGS ((1L << SIGTTIN)|(1L << SIGTTOU)|(1L << SIGTSTP)|(1L << SIGSTOP))

/* POSIX real-time signal extensions */

#ifndef _SIGVAL_DEFINED
#define _SIGVAL_DEFINED

/* Signal value union - use kernel types */
union sigval {
	long sival_int;        /* Integer value (use long for portability) */
	void *sival_ptr;       /* Pointer value */
};

#endif /* _SIGVAL_DEFINED */

#ifndef _SIGINFO_T_DEFINED
#define _SIGINFO_T_DEFINED

/* siginfo_t structure for extended signal information */
typedef struct {
	int si_signo;           /* Signal number */
	int si_code;            /* Signal code */
	int si_errno;           /* If non-zero, an errno value */
	short si_pid;           /* Sending process ID (use short like kernel pid) */
	unsigned short si_uid;  /* Real user ID (use unsigned short) */
	void *si_addr;          /* Address of faulting instruction */
	int si_status;          /* Exit value or signal */
	long si_band;           /* Band event for SIGPOLL */
	union sigval si_value;  /* Signal value */
} siginfo_t;

#endif /* _SIGINFO_T_DEFINED */

/* Signal codes for si_code */
#define SI_USER        0x0001    /* Signal sent by kill() or raise() */
#define SI_QUEUE       0x0002    /* Signal sent by sigqueue() */
#define SI_TIMER       0x0003    /* Signal generated by timer expiration */
#define SI_ASYNCIO     0x0004    /* Signal generated by async I/O completion */
#define SI_MESGQ       0x0005    /* Signal generated by message arrival */

/* For SIGCHLD */
#define CLD_EXITED     0x0601    /* Child has exited */
#define CLD_KILLED     0x0602    /* Child was killed */
#define CLD_DUMPED     0x0603    /* Child terminated abnormally */
#define CLD_TRAPPED    0x0604    /* Traced child has trapped */
#define CLD_STOPPED    0x0605    /* Child has stopped */
#define CLD_CONTINUED  0x0606    /* Stopped child has continued */

/* Wait condition for sigwait functions */
#define WAIT_SIGWAIT    0x3a140004L


/* sigaction: extended POSIX signal handling facility
 */
struct sigaction
{
	unsigned long  sa_handler;	/* pointer to signal handler */
	unsigned long  sa_mask;		/* additional signals masked during delivery */
	unsigned short sa_flags;	/* signal specific flags */
	// void (*sa_sigaction)(int, siginfo_t *, void *); /* POSIX extension */
};

/* signal handler values */
# define SIG_ERR	-1
# define SIG_DFL	 0
# define SIG_IGN	 1

/* signal flags */
# define SA_ONSTACK	0x2000		/* take signal on signal stack */
# define SA_RESTART	0x4000		/* restart system on signal return */
# define SA_RESETHAND	0x8000		/* reset to SIG_DFL just before delivery */
# define SA_NODEFER	0x0010		/* don't mask the signal we're delivering */
# define SA_SIGINFO	0x0040
/* only valid for SIGCHLD */
# define SA_NOCLDSTOP	0x0001		/* don't send SIGCHLD when child stops */
# define SA_NOCLDWAIT	0x0002		/* do not generate zombies on unwaited child */
# define SA_ALLBITS	0x007f

# define SAUSER		(SA_NODEFER | SA_NOCLDSTOP | SA_RESETHAND)	/* XXX signal flags which the process may set */
# define SAPARENT	(0)		/* XXX signal flags which the parent (of ptraced) processes may set */
# define SAKERNEL	(0)	/* XXX kernel only flags */

/* values for ss_flags */
# define SS_ONSTACK	1
# define SS_DISABLE	2

# define MINSIGSTKSZ	2048		/* minimum stack size */
# define SIGSTKSZ	8192		/* default stack size */

typedef struct sigaltstack
{
	void *ss_sp;
	long ss_flags;
	unsigned long ss_size;
}
stack_t;

struct sigacts
{
	struct sigaction sigact[NSIG];	/* disposition of signals */
	stack_t sigstk;			/* sp & on stack state variable */
	sigset_t oldmask;		/* saved mask from before sigpause */
	long flags;			/* signal flags, below */
	long links;			/* reference count */
	/* Extended signal handlers for SA_SIGINFO */
	void (*sa_sigaction_ext[NSIG])(int, siginfo_t *, void *);
	/* Thread-specific signal handling */
	int thread_signals;             /* 1 if thread-specific signals enabled */
};

/* helper macro */
# define SIGACTION(p, sig)		((p)->p_sigacts->sigact[(sig)])

# endif /* _mint_signal_h */
